### ISSUE TITLE
运行docker环境，启动示例demo，enable_curobo报错，不采用enable_curobo机器人没有动作

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [AgibotTech/genie_sim#4]
您好，在运行时遇到了如下问题：
不采用corobo
```
# start a new container in main direcory
# you need to change ~/assets to GenieSimAssets folder
SIM_ASSETS=~/assets ./scripts/start_gui.sh
./scripts/into.sh

# start server in container
omni_python server/source/genie.sim.lab/raise_standalone_sim.py
```

```
# start container in main directory
./scripts/into.sh

# start client in container
omni_python benchmark/task_benchmark.py --task_name=genie_task_supermarket
```

机器人一直停留在一个状态没有动作

![Image](https://github.com/user-attachments/assets/b2fcec93-0d92-4cb3-ad54-2857bfb3401f)

![Image](https://github.com/user-attachments/assets/444b5235-9aae-4d93-ad59-17d457439760)

### 采用curobo

在server启动时，出现 报错
```
# start a new container in main direcory
# you need to change ~/assets to GenieSimAssets folder
SIM_ASSETS=~/assets ./scripts/start_gui.sh
./scripts/into.sh

# start server
omni_python server/source/genie.sim.lab/raise_standalone_sim.py --enable_curobo True # The grasp trajectory of this demo is generated by Curobo

```
出现报错
```
2025-04-25 01:55:38 [181,782ms] [Error] [omni.kit.app._impl] [py stderr]: Traceback (most recent call last):
2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/raise_standalone_sim.py", line 108, in <module>
2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:     main()
2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/raise_standalone_sim.py", line 99, in main
2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:     rpc_server.server_function.on_physics_step()
2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 239, in on_physics_step
2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:     self.on_command_step()
2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 768, in on_command_step
2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_robot_cfg(
2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 192, in _init_robot_cfg
2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:     self._play()
2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 196, in _play
2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_robot(self.robot_cfg, self.enable_curobo)
2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 215, in _init_robot
2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:     self.ui_builder._init_solver(robot, enable_curobo, self.batch_num)
2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 84, in _init_solver
2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:     self.initialize_articulation(batch_num)
2025-04-25 01:55:38 [181,786ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 604, in initialize_articulation
2025-04-25 01:55:38 [181,786ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_curobo()
2025-04-25 01:55:38 [181,786ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 661, in _init_curobo
2025-04-25 01:55:38 [181,786ms] [Error] [omni.kit.app._impl] [py stderr]:     self.curoboMotion = CuroboMotion(
2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/utils/motion_gen_reacher.py", line 98, in __init__
2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:     motion_gen_config = MotionGen.load_from_robot_config(
2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/wrap/reacher/motion_gen.py", line 612, in load_from_robot_config
2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:     robot_cfg = RobotConfig.from_dict(robot_cfg, tensor_args)
2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/types/robot.py", line 50, in from_dict
2025-04-25 01:55:38 [181,788ms] [Error] [omni.kit.app._impl] [py stderr]:     data_dict["kinematics"] = CudaRobotModelConfig.from_config(
2025-04-25 01:55:38 [181,788ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_model.py", line 248, in from_config
2025-04-25 01:55:38 [181,789ms] [Error] [omni.kit.app._impl] [py stderr]:     generator = CudaRobotGenerator(config)
2025-04-25 01:55:38 [181,789ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 260, in __init__
2025-04-25 01:55:38 [181,790ms] [Error] [omni.kit.app._impl] [py stderr]:     self.initialize_tensors()
2025-04-25 01:55:38 [181,790ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
2025-04-25 01:55:38 [181,790ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
2025-04-25 01:55:38 [181,790ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 337, in initialize_tensors
2025-04-25 01:55:38 [181,791ms] [Error] [omni.kit.app._impl] [py stderr]:     self._build_kinematics_with_lock_joints(
2025-04-25 01:55:38 [181,791ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
2025-04-25 01:55:38 [181,791ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
2025-04-25 01:55:38 [181,791ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 673, in _build_kinematics_with_lock_joints
2025-04-25 01:55:38 [181,792ms] [Error] [omni.kit.app._impl] [py stderr]:     link_poses = self._get_link_poses(q, lock_links, kinematics_config)
2025-04-25 01:55:38 [181,792ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
2025-04-25 01:55:38 [181,792ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
2025-04-25 01:55:38 [181,792ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 1072, in _get_link_poses
2025-04-25 01:55:38 [181,793ms] [Error] [omni.kit.app._impl] [py stderr]:     link_pos_seq, link_quat_seq, _ = get_cuda_kinematics(
2025-04-25 01:55:38 [181,793ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/curobolib/kinematics.py", line 250, in get_cuda_kinematics
2025-04-25 01:55:38 [181,793ms] [Error] [omni.kit.app._impl] [py stderr]:     link_pos, link_quat, robot_spheres = KinematicsFusedFunction.apply(
2025-04-25 01:55:38 [181,793ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/exts/omni.isaac.ml_archive/pip_prebundle/torch/autograd/function.py", line 575, in apply
2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/curobolib/kinematics.py", line 73, in forward
2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]:     r = kinematics_fused_cu.forward(
2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]: RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]: 


```

经测试，torch的cuda是available并且可以使用cuda跑程序，初步确定应该不是docker中cuda和torch的问题

**Comment by dogchenya** [comment]
> 您好，在运行时遇到了如下问题： 不采用corobo
> 
> ```
> # start a new container in main direcory
> # you need to change ~/assets to GenieSimAssets folder
> SIM_ASSETS=~/assets ./scripts/start_gui.sh
> ./scripts/into.sh
> 
> # start server in container
> omni_python server/source/genie.sim.lab/raise_standalone_sim.py
> ```
> 
> ```
> # start container in main directory
> ./scripts/into.sh
> 
> # start client in container
> omni_python benchmark/task_benchmark.py --task_name=genie_task_supermarket
> ```
> 
> 机器人一直停留在一个状态没有动作
> 
> ![Image](https://github.com/user-attachments/assets/b2fcec93-0d92-4cb3-ad54-2857bfb3401f)
> 
> ![Image](https://github.com/user-attachments/assets/444b5235-9aae-4d93-ad59-17d457439760)
> 
> ### 采用curobo
> 在server启动时，出现 报错
> 
> ```
> # start a new container in main direcory
> # you need to change ~/assets to GenieSimAssets folder
> SIM_ASSETS=~/assets ./scripts/start_gui.sh
> ./scripts/into.sh
> 
> # start server
> omni_python server/source/genie.sim.lab/raise_standalone_sim.py --enable_curobo True # The grasp trajectory of this demo is generated by Curobo
> ```
> 
> 出现报错
> 
> ```
> 2025-04-25 01:55:38 [181,782ms] [Error] [omni.kit.app._impl] [py stderr]: Traceback (most recent call last):
> 2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/raise_standalone_sim.py", line 108, in <module>
> 2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:     main()
> 2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/raise_standalone_sim.py", line 99, in main
> 2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:     rpc_server.server_function.on_physics_step()
> 2025-04-25 01:55:38 [181,783ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 239, in on_physics_step
> 2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:     self.on_command_step()
> 2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 768, in on_command_step
> 2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_robot_cfg(
> 2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 192, in _init_robot_cfg
> 2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:     self._play()
> 2025-04-25 01:55:38 [181,784ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 196, in _play
> 2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_robot(self.robot_cfg, self.enable_curobo)
> 2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 215, in _init_robot
> 2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:     self.ui_builder._init_solver(robot, enable_curobo, self.batch_num)
> 2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 84, in _init_solver
> 2025-04-25 01:55:38 [181,785ms] [Error] [omni.kit.app._impl] [py stderr]:     self.initialize_articulation(batch_num)
> 2025-04-25 01:55:38 [181,786ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 604, in initialize_articulation
> 2025-04-25 01:55:38 [181,786ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_curobo()
> 2025-04-25 01:55:38 [181,786ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 661, in _init_curobo
> 2025-04-25 01:55:38 [181,786ms] [Error] [omni.kit.app._impl] [py stderr]:     self.curoboMotion = CuroboMotion(
> 2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/utils/motion_gen_reacher.py", line 98, in __init__
> 2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:     motion_gen_config = MotionGen.load_from_robot_config(
> 2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/wrap/reacher/motion_gen.py", line 612, in load_from_robot_config
> 2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:     robot_cfg = RobotConfig.from_dict(robot_cfg, tensor_args)
> 2025-04-25 01:55:38 [181,787ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/types/robot.py", line 50, in from_dict
> 2025-04-25 01:55:38 [181,788ms] [Error] [omni.kit.app._impl] [py stderr]:     data_dict["kinematics"] = CudaRobotModelConfig.from_config(
> 2025-04-25 01:55:38 [181,788ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_model.py", line 248, in from_config
> 2025-04-25 01:55:38 [181,789ms] [Error] [omni.kit.app._impl] [py stderr]:     generator = CudaRobotGenerator(config)
> 2025-04-25 01:55:38 [181,789ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 260, in __init__
> 2025-04-25 01:55:38 [181,790ms] [Error] [omni.kit.app._impl] [py stderr]:     self.initialize_tensors()
> 2025-04-25 01:55:38 [181,790ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
> 2025-04-25 01:55:38 [181,790ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
> 2025-04-25 01:55:38 [181,790ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 337, in initialize_tensors
> 2025-04-25 01:55:38 [181,791ms] [Error] [omni.kit.app._impl] [py stderr]:     self._build_kinematics_with_lock_joints(
> 2025-04-25 01:55:38 [181,791ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
> 2025-04-25 01:55:38 [181,791ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
> 2025-04-25 01:55:38 [181,791ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 673, in _build_kinematics_with_lock_joints
> 2025-04-25 01:55:38 [181,792ms] [Error] [omni.kit.app._impl] [py stderr]:     link_poses = self._get_link_poses(q, lock_links, kinematics_config)
> 2025-04-25 01:55:38 [181,792ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
> 2025-04-25 01:55:38 [181,792ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
> 2025-04-25 01:55:38 [181,792ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 1072, in _get_link_poses
> 2025-04-25 01:55:38 [181,793ms] [Error] [omni.kit.app._impl] [py stderr]:     link_pos_seq, link_quat_seq, _ = get_cuda_kinematics(
> 2025-04-25 01:55:38 [181,793ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/curobolib/kinematics.py", line 250, in get_cuda_kinematics
> 2025-04-25 01:55:38 [181,793ms] [Error] [omni.kit.app._impl] [py stderr]:     link_pos, link_quat, robot_spheres = KinematicsFusedFunction.apply(
> 2025-04-25 01:55:38 [181,793ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/exts/omni.isaac.ml_archive/pip_prebundle/torch/autograd/function.py", line 575, in apply
> 2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
> 2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/curobolib/kinematics.py", line 73, in forward
> 2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]:     r = kinematics_fused_cu.forward(
> 2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]: RuntimeError: CUDA error: no kernel image is available for execution on the device
> CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
> For debugging consider passing CUDA_LAUNCH_BLOCKING=1
> Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
> 2025-04-25 01:55:38 [181,794ms] [Error] [omni.kit.app._impl] [py stderr]: 
> ```
> 
> 经测试，torch的cuda是available并且可以使用cuda跑程序，初步确定应该不是docker中cuda和torch的问题

1. curobo 非在当前的显卡架构编译会出此问题，
或许可以release option1，在 ./scripts/dockerfile，注掉 option2，本地编译curobo
RUN git clone https://github.com/NVlabs/curobo.git --depth 1 /tmp/curobo
RUN cd /tmp/curobo && /isaac-sim/python.sh -m pip install .[isaacsim] -i https://pypi.tuna.tsinghua.edu.cn/simple
2. 需要机器人有动作，需要接入模型，我们提供的demo 是curobo实现移动并示例如何操作机器人

**Comment by yonhdee** [comment]
can you provide your system info like below, it looks like a mismatched version between curobo and cuda

**System Info**
Describe the characteristic of your environment:

OS: Ubuntu 22.04
GPU: RTX 4090 (24GB RAM version)
CUDA: 12.8
GPU Driver: 535.183.01

**nvidia-smi**
```bash
Fri Apr 25 03:18:16 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0  On |                  Off |
| 43%   54C    P0             97W /  425W |    1433MiB /  24564MiB |     51%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

**Comment by Ethan-Chen-plus** [comment]
> 
> 1. curobo 非在当前的显卡架构编译会出此问题，
>    或许可以release option1，在 ./scripts/dockerfile，注掉 option2，本地编译curobo
>    RUN git clone https://github.com/NVlabs/curobo.git --depth 1 /tmp/curobo
>    RUN cd /tmp/curobo && /isaac-sim/python.sh -m pip install .[isaacsim] -i https://pypi.tuna.tsinghua.edu.cn/simple
> 2. 需要机器人有动作，需要接入模型，我们提供的demo 是curobo实现移动并示例如何操作机器人

您好@dogchenya

采用源码安装会出现报错：
```
kewei@sxy-gpus3090:~/17robo/genie_sim$ docker build -f ./scripts/dockerfile -t registry.agibot.com/genie-sim/open_source:latest .
[+] Building 522.8s (16/18)                                                                      docker:default
 => [internal] load build definition from dockerfile                                                       0.0s
 => => transferring dockerfile: 2.99kB                                                                     0.0s
 => [internal] load metadata for nvcr.io/nvidia/isaac-sim:4.5.0                                            1.4s
 => [internal] load .dockerignore                                                                          0.0s
 => => transferring context: 2B                                                                            0.0s
 => [ 1/14] FROM nvcr.io/nvidia/isaac-sim:4.5.0@sha256:c2f47dc82a7714af08d3766efe80ac9d084c2b37b5d0dfbd07  0.0s
 => [internal] load build context                                                                          0.0s
 => => transferring context: 141B                                                                          0.0s
 => CACHED [ 2/14] RUN apt-get update && apt-get install -y     build-essential     cmake     libeigen3-d  0.0s
 => CACHED [ 3/14] RUN echo 'Etc/UTC' > /etc/timezone &&     ln -s /usr/share/zoneinfo/Etc/UTC /etc/local  0.0s
 => CACHED [ 4/14] RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8   0.0s
 => CACHED [ 5/14] RUN add-apt-repository universe &&     curl -sSL https://raw.githubusercontent.com/ros  0.0s
 => CACHED [ 6/14] RUN apt-get update && apt-get -y upgrade &&     apt-get install -q -y --no-install-rec  0.0s
 => CACHED [ 7/14] COPY ./requirements.txt /tmp                                                            0.0s
 => CACHED [ 8/14] RUN /isaac-sim/kit/python/bin/python3 -m pip install --upgrade pip -i https://pypi.tun  0.0s
 => CACHED [ 9/14] RUN /isaac-sim/python.sh -m pip install -r /tmp/requirements.txt -i https://pypi.tuna.  0.0s
 => CACHED [10/14] RUN /isaac-sim/python.sh -m pip install tomli wheel ninja -i https://pypi.tuna.tsinghu  0.0s
 => [11/14] RUN git clone https://github.com/NVlabs/curobo.git --depth 1 /tmp/curobo                     316.7s
 => ERROR [12/14] RUN cd /tmp/curobo && /isaac-sim/python.sh -m pip install .[isaacsim] -i https://pypi  204.3s
------
 > [12/14] RUN cd /tmp/curobo && /isaac-sim/python.sh -m pip install .[isaacsim] -i https://pypi.tuna.tsinghua.edu.cn/simple:
5.173 Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
5.173 Processing /tmp/curobo
5.296   Installing build dependencies: started
67.24   Installing build dependencies: still running...
193.0   Installing build dependencies: still running...
194.5   Installing build dependencies: finished with status 'done'
194.5   Getting requirements to build wheel: started
199.8   Getting requirements to build wheel: finished with status 'error'
199.8   error: subprocess-exited-with-error
199.8   
199.8   × Getting requirements to build wheel did not run successfully.
199.8   │ exit code: 1
199.8   ╰─> [23 lines of output]
199.8       /tmp/pip-build-env-cyoo3tps/overlay/lib/python3.10/site-packages/torch/_subclasses/functional_tensor.py:276: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:81.)
199.8         cpu = _conversion_method_template(device=torch.device("cpu"))
199.8       Traceback (most recent call last):
199.8         File "/isaac-sim/kit/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
199.8           main()
199.8         File "/isaac-sim/kit/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
199.8           json_out["return_val"] = hook(**hook_input["kwargs"])
199.8         File "/isaac-sim/kit/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
199.8           return hook(config_settings)
199.8         File "/tmp/pip-build-env-cyoo3tps/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 331, in get_requires_for_build_wheel
199.8           return self._get_build_requires(config_settings, requirements=[])
199.8         File "/tmp/pip-build-env-cyoo3tps/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 301, in _get_build_requires
199.8           self.run_setup()
199.8         File "/tmp/pip-build-env-cyoo3tps/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 317, in run_setup
199.8           exec(code, locals())
199.8         File "<string>", line 43, in <module>
199.8         File "/tmp/pip-build-env-cyoo3tps/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1279, in CUDAExtension
199.8           library_dirs += library_paths(device_type="cuda")
199.8         File "/tmp/pip-build-env-cyoo3tps/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1490, in library_paths
199.8           if (not os.path.exists(_join_cuda_home(lib_dir)) and
199.8         File "/tmp/pip-build-env-cyoo3tps/overlay/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2889, in _join_cuda_home
199.8           raise OSError('CUDA_HOME environment variable is not set. '
199.8       OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
199.8       [end of output]
199.8   
199.8   note: This error originates from a subprocess, and is likely not a problem with pip.
199.9 error: subprocess-exited-with-error
199.9 
199.9 × Getting requirements to build wheel did not run successfully.
199.9 │ exit code: 1
199.9 ╰─> See above for output.
199.9 
199.9 note: This error originates from a subprocess, and is likely not a problem with pip.
203.9 There was an error running python
------
dockerfile:58
--------------------
  56 |     # - option1: install from source, which can be slow, please refer to https://curobo.org/get_started/1_install_instructions.html
  57 |     RUN git clone https://github.com/NVlabs/curobo.git --depth 1 /tmp/curobo
  58 | >>> RUN cd /tmp/curobo && /isaac-sim/python.sh -m pip install .[isaacsim] -i https://pypi.tuna.tsinghua.edu.cn/simple
  59 |     # - option2: install from pre-built wheel
  60 |     # COPY 3rdparty/nvidia_curobo-0.7.6-cp310-cp310-linux_x86_64.whl /tmp
--------------------
ERROR: failed to solve: process "/bin/sh -c cd /tmp/curobo && /isaac-sim/python.sh -m pip install .[isaacsim] -i https://pypi.tuna.tsinghua.edu.cn/simple" did not complete successfully: exit code: 1
```

**Comment by Ethan-Chen-plus** [comment]
> can you provide your system info like below, it looks like a mismatched version between curobo and cuda
> 
> **System Info** Describe the characteristic of your environment:
> 
> OS: Ubuntu 22.04 GPU: RTX 4090 (24GB RAM version) CUDA: 12.8 GPU Driver: 535.183.01
> 
> **nvidia-smi**
> 
> Fri Apr 25 03:18:16 2025       
> +-----------------------------------------------------------------------------------------+
> | NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
> |-----------------------------------------+------------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> |                                         |                        |               MIG M. |
> |=========================================+========================+======================|
> |   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0  On |                  Off |
> | 43%   54C    P0             97W /  425W |    1433MiB /  24564MiB |     51%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
>                                                                                          
> +-----------------------------------------------------------------------------------------+
> | Processes:                                                                              |
> |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
> |        ID   ID                                                               Usage      |
> |=========================================================================================|
> +-----------------------------------------------------------------------------------------+

Thanks!@yonhdee
Below is mine:
**System Info**  
Describe the characteristic of your environment:

OS: Ubuntu 22.04.5 LTS  
GPU: RTX 3090*4 (24GB RAM version)  
CUDA: 12.8  
GPU Driver: 570.124.04   

**nvidia-smi**
```
nvidia-smi
Fri Apr 25 06:22:23 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.124.04             Driver Version: 570.124.04     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3090        Off |   00000000:03:00.0 Off |                  N/A |
| 32%   44C    P0            116W /  350W |   10950MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   1  NVIDIA GeForce RTX 3090        Off |   00000000:03:02.0 Off |                  N/A |
| 63%   60C    P0            184W /  350W |   17762MiB /  24576MiB |     15%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   2  NVIDIA GeForce RTX 3090        Off |   00000000:03:04.0 Off |                  N/A |
| 60%   76C    P0            213W /  370W |   20028MiB /  24576MiB |     30%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
|   3  NVIDIA GeForce RTX 3090        Off |   00000000:03:06.0 Off |                  N/A |
| 57%   53C    P0            113W /  350W |    5028MiB /  24576MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A          673227      C   python                                10536MiB |
|    0   N/A  N/A          870880    C+G   ./kit/kit                               258MiB |
|    0   N/A  N/A         1101432      G   python                                  118MiB |
|    1   N/A  N/A          870880      C   ./kit/kit                               254MiB |
|    1   N/A  N/A         1239259      C   python                                17490MiB |
|    2   N/A  N/A          870880      C   ./kit/kit                               254MiB |
|    2   N/A  N/A         1239259      C   python                                19756MiB |
|    3   N/A  N/A          870880      C   ./kit/kit                               254MiB |
|    3   N/A  N/A         1101432      C   python                                 4754MiB |
+-----------------------------------------------------------------------------------------+
```

**Comment by yonhdee** [comment]
can you provide your system info like below, it looks like a mismatched version between curobo and cuda

**System Info**
Describe the characteristic of your environment:

OS: Ubuntu 22.04
GPU: RTX 4090 (24GB RAM version)
CUDA: 12.8
GPU Driver: 535.183.01

**nvidia-smi**
```bash
Fri Apr 25 03:18:16 2025       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0  On |                  Off |
| 43%   54C    P0             97W /  425W |    1433MiB /  24564MiB |     51%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
+-----------------------------------------------------------------------------------------+
```

> > can you provide your system info like below, it looks like a mismatched version between curobo and cuda
> > **System Info** Describe the characteristic of your environment:
> > OS: Ubuntu 22.04 GPU: RTX 4090 (24GB RAM version) CUDA: 12.8 GPU Driver: 535.183.01
> > **nvidia-smi**
> > Fri Apr 25 03:18:16 2025
> > +-----------------------------------------------------------------------------------------+
> > | NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
> > |-----------------------------------------+------------------------+----------------------+
> > | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> > | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> > |                                         |                        |               MIG M. |
> > |=========================================+========================+======================|
> > |   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0  On |                  Off |
> > | 43%   54C    P0             97W /  425W |    1433MiB /  24564MiB |     51%      Default |
> > |                                         |                        |                  N/A |
> > +-----------------------------------------+------------------------+----------------------+
> > +-----------------------------------------------------------------------------------------+
> > | Processes:                                                                              |
> > |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
> > |        ID   ID                                                               Usage      |
> > |=========================================================================================|
> > +-----------------------------------------------------------------------------------------+
> 
> Thanks![@yonhdee](https://github.com/yonhdee) Below is mine: **System Info** Describe the characteristic of your environment:
> 
> OS: Ubuntu 22.04.5 LTS GPU: RTX 3090*4 (24GB RAM version) CUDA: 12.8 GPU Driver: 570.124.04
> 
> **nvidia-smi**
> 
> ```
> nvidia-smi
> Fri Apr 25 06:22:23 2025       
> +-----------------------------------------------------------------------------------------+
> | NVIDIA-SMI 570.124.04             Driver Version: 570.124.04     CUDA Version: 12.8     |
> |-----------------------------------------+------------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> |                                         |                        |               MIG M. |
> |=========================================+========================+======================|
> |   0  NVIDIA GeForce RTX 3090        Off |   00000000:03:00.0 Off |                  N/A |
> | 32%   44C    P0            116W /  350W |   10950MiB /  24576MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> |   1  NVIDIA GeForce RTX 3090        Off |   00000000:03:02.0 Off |                  N/A |
> | 63%   60C    P0            184W /  350W |   17762MiB /  24576MiB |     15%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> |   2  NVIDIA GeForce RTX 3090        Off |   00000000:03:04.0 Off |                  N/A |
> | 60%   76C    P0            213W /  370W |   20028MiB /  24576MiB |     30%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
> |   3  NVIDIA GeForce RTX 3090        Off |   00000000:03:06.0 Off |                  N/A |
> | 57%   53C    P0            113W /  350W |    5028MiB /  24576MiB |      0%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
>                                                                                          
> +-----------------------------------------------------------------------------------------+
> | Processes:                                                                              |
> |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
> |        ID   ID                                                               Usage      |
> |=========================================================================================|
> |    0   N/A  N/A          673227      C   python                                10536MiB |
> |    0   N/A  N/A          870880    C+G   ./kit/kit                               258MiB |
> |    0   N/A  N/A         1101432      G   python                                  118MiB |
> |    1   N/A  N/A          870880      C   ./kit/kit                               254MiB |
> |    1   N/A  N/A         1239259      C   python                                17490MiB |
> |    2   N/A  N/A          870880      C   ./kit/kit                               254MiB |
> |    2   N/A  N/A         1239259      C   python                                19756MiB |
> |    3   N/A  N/A          870880      C   ./kit/kit                               254MiB |
> |    3   N/A  N/A         1101432      C   python                                 4754MiB |
> +-----------------------------------------------------------------------------------------+
> ```

pls check this branch, there's a quick fix for install curobo from source duration docker image building
> https://github.com/AgibotTech/genie_sim/tree/fix/curobo

**Comment by Ethan-Chen-plus** [comment]
> can you provide your system info like below, it looks like a mismatched version between curobo and cuda
> 
> **System Info** Describe the characteristic of your environment:
> 
> OS: Ubuntu 22.04 GPU: RTX 4090 (24GB RAM version) CUDA: 12.8 GPU Driver: 535.183.01
> 
> **nvidia-smi**
> 
> Fri Apr 25 03:18:16 2025       
> +-----------------------------------------------------------------------------------------+
> | NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
> |-----------------------------------------+------------------------+----------------------+
> | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> |                                         |                        |               MIG M. |
> |=========================================+========================+======================|
> |   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0  On |                  Off |
> | 43%   54C    P0             97W /  425W |    1433MiB /  24564MiB |     51%      Default |
> |                                         |                        |                  N/A |
> +-----------------------------------------+------------------------+----------------------+
>                                                                                          
> +-----------------------------------------------------------------------------------------+
> | Processes:                                                                              |
> |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
> |        ID   ID                                                               Usage      |
> |=========================================================================================|
> +-----------------------------------------------------------------------------------------+
> > > can you provide your system info like below, it looks like a mismatched version between curobo and cuda
> > > **System Info** Describe the characteristic of your environment:
> > > OS: Ubuntu 22.04 GPU: RTX 4090 (24GB RAM version) CUDA: 12.8 GPU Driver: 535.183.01
> > > **nvidia-smi**
> > > Fri Apr 25 03:18:16 2025
> > > +-----------------------------------------------------------------------------------------+
> > > | NVIDIA-SMI 570.133.20             Driver Version: 570.133.20     CUDA Version: 12.8     |
> > > |-----------------------------------------+------------------------+----------------------+
> > > | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> > > | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> > > |                                         |                        |               MIG M. |
> > > |=========================================+========================+======================|
> > > |   0  NVIDIA GeForce RTX 4090 D      Off |   00000000:01:00.0  On |                  Off |
> > > | 43%   54C    P0             97W /  425W |    1433MiB /  24564MiB |     51%      Default |
> > > |                                         |                        |                  N/A |
> > > +-----------------------------------------+------------------------+----------------------+
> > > +-----------------------------------------------------------------------------------------+
> > > | Processes:                                                                              |
> > > |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
> > > |        ID   ID                                                               Usage      |
> > > |=========================================================================================|
> > > +-----------------------------------------------------------------------------------------+
> > 
> > 
> > Thanks![@yonhdee](https://github.com/yonhdee) Below is mine: **System Info** Describe the characteristic of your environment:
> > OS: Ubuntu 22.04.5 LTS GPU: RTX 3090*4 (24GB RAM version) CUDA: 12.8 GPU Driver: 570.124.04
> > **nvidia-smi**
> > ```
> > nvidia-smi
> > Fri Apr 25 06:22:23 2025       
> > +-----------------------------------------------------------------------------------------+
> > | NVIDIA-SMI 570.124.04             Driver Version: 570.124.04     CUDA Version: 12.8     |
> > |-----------------------------------------+------------------------+----------------------+
> > | GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
> > | Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
> > |                                         |                        |               MIG M. |
> > |=========================================+========================+======================|
> > |   0  NVIDIA GeForce RTX 3090        Off |   00000000:03:00.0 Off |                  N/A |
> > | 32%   44C    P0            116W /  350W |   10950MiB /  24576MiB |      0%      Default |
> > |                                         |                        |                  N/A |
> > +-----------------------------------------+------------------------+----------------------+
> > |   1  NVIDIA GeForce RTX 3090        Off |   00000000:03:02.0 Off |                  N/A |
> > | 63%   60C    P0            184W /  350W |   17762MiB /  24576MiB |     15%      Default |
> > |                                         |                        |                  N/A |
> > +-----------------------------------------+------------------------+----------------------+
> > |   2  NVIDIA GeForce RTX 3090        Off |   00000000:03:04.0 Off |                  N/A |
> > | 60%   76C    P0            213W /  370W |   20028MiB /  24576MiB |     30%      Default |
> > |                                         |                        |                  N/A |
> > +-----------------------------------------+------------------------+----------------------+
> > |   3  NVIDIA GeForce RTX 3090        Off |   00000000:03:06.0 Off |                  N/A |
> > | 57%   53C    P0            113W /  350W |    5028MiB /  24576MiB |      0%      Default |
> > |                                         |                        |                  N/A |
> > +-----------------------------------------+------------------------+----------------------+
> >                                                                                          
> > +-----------------------------------------------------------------------------------------+
> > | Processes:                                                                              |
> > |  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
> > |        ID   ID                                                               Usage      |
> > |=========================================================================================|
> > |    0   N/A  N/A          673227      C   python                                10536MiB |
> > |    0   N/A  N/A          870880    C+G   ./kit/kit                               258MiB |
> > |    0   N/A  N/A         1101432      G   python                                  118MiB |
> > |    1   N/A  N/A          870880      C   ./kit/kit                               254MiB |
> > |    1   N/A  N/A         1239259      C   python                                17490MiB |
> > |    2   N/A  N/A          870880      C   ./kit/kit                               254MiB |
> > |    2   N/A  N/A         1239259      C   python                                19756MiB |
> > |    3   N/A  N/A          870880      C   ./kit/kit                               254MiB |
> > |    3   N/A  N/A         1101432      C   python                                 4754MiB |
> > +-----------------------------------------------------------------------------------------+
> > ```
> 
> pls check this branch, there's a quick fix for install curobo from source duration docker image building
> 
> > https://github.com/AgibotTech/genie_sim/tree/fix/curobo

Thanks a lot! It seems work ok! Now I will try to explore curobo to test IK and pick things. Could you keep this issue open for a while? Thanks a lot!

**Comment by yonhdee** [comment]
sure thing

**Comment by Ethan-Chen-plus** [comment]
> sure thing

Hi! Are you still here?
I have build the docker:
```
docker build -f ./scripts/dockerfile -t registry.agibot.com/genie-sim/open_source:latest .
[+] Building 1856.8s (24/24) FINISHED                                         docker:default
 => [internal] load build definition from dockerfile                                    0.0s
 => => transferring dockerfile: 3.29kB                                                  0.0s
 => [internal] load metadata for nvcr.io/nvidia/isaac-sim:4.5.0                         0.8s
 => [internal] load .dockerignore                                                       0.0s
 => => transferring context: 2B                                                         0.0s
 => [ 1/19] FROM nvcr.io/nvidia/isaac-sim:4.5.0@sha256:c2f47dc82a7714af08d3766efe80ac9  0.0s
 => [internal] load build context                                                       0.0s
 => => transferring context: 1.06kB                                                     0.0s
 => CACHED [ 2/19] RUN apt-get update && apt-get install -y     build-essential     cm  0.0s
 => CACHED [ 3/19] RUN echo 'Etc/UTC' > /etc/timezone &&     ln -s /usr/share/zoneinfo  0.0s
 => CACHED [ 4/19] RUN locale-gen en_US en_US.UTF-8 && update-locale LC_ALL=en_US.UTF-  0.0s
 => CACHED [ 5/19] RUN add-apt-repository universe &&     curl -sSL https://raw.github  0.0s
 => CACHED [ 6/19] RUN apt-get update && apt-get -y upgrade &&     apt-get install -q   0.0s
 => CACHED [ 7/19] COPY ./requirements.txt /tmp                                         0.0s
 => CACHED [ 8/19] RUN /isaac-sim/kit/python/bin/python3 -m pip install --upgrade pip   0.0s
 => CACHED [ 9/19] RUN /isaac-sim/python.sh -m pip install -r /tmp/requirements.txt -i  0.0s
 => CACHED [10/19] RUN /isaac-sim/python.sh -m pip install tomli wheel ninja -i https:  0.0s
 => CACHED [11/19] RUN git clone https://github.com/NVlabs/curobo.git --depth 1 /tmp/c  0.0s
 => CACHED [12/19] RUN cd /tmp && wget https://developer.download.nvidia.com/compute/c  0.0s
 => CACHED [13/19] RUN dpkg -i /tmp/cuda-keyring_1.0-1_all.deb                          0.0s
 => CACHED [14/19] RUN apt-get update                                                   0.0s
 => [15/19] RUN apt-get -y install cuda-toolkit-11-8                                  286.8s
 => [16/19] RUN cd /tmp/curobo && /isaac-sim/python.sh -m pip install --no-build-is  1460.1s
 => [17/19] COPY ./server/source/genie.sim.lab/curobo /isaac-sim/kit/python/lib/python  0.1s
 => [18/19] COPY 3rdparty/ik_solver-0.3.0-cp310-cp310-linux_x86_64.whl /tmp             1.0s
 => [19/19] RUN /isaac-sim/python.sh -m pip install -i https://pypi.tuna.tsinghua.edu.  7.8s
 => exporting to image                                                                 99.5s
 => => exporting layers                                                                98.9s
 => => writing image sha256:a670f8e44274511c9d6db950b8d922dc1169226781741a894a5ed1daf1  0.3s
 => => naming to registry.agibot.com/genie-sim/open_source:latest                       0.1s
kewei@sxy-gpus3090:~/17robo/genie_sim$ 
```
There are also some problems in the fix/curobo branch when start server:

```
2025-04-25 16:12:04 [181,178ms] [Warning] [omni.physx.plugin] The rigid body at /G1/gripper_center has a possibly invalid inertia tensor of {1.0, 1.0, 1.0} and a negative mass, small sphere approximated inertia was used. Either specify correct values in the mass properties, or add collider(s) to any shape(s) that you wish to automatically compute mass properties for.
2025-04-25 16:12:04 [181,180ms] [Warning] [omni.physx.plugin] The rigid body at /G1/right_gripper_center has a possibly invalid inertia tensor of {1.0, 1.0, 1.0} and a negative mass, small sphere approximated inertia was used. Either specify correct values in the mass properties, or add collider(s) to any shape(s) that you wish to automatically compute mass properties for.
2025-04-25 16:13:19 [256,058ms] [Error] [omni.kit.app._impl] [py stderr]: Traceback (most recent call last):
2025-04-25 16:13:19 [256,059ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/raise_standalone_sim.py", line 108, in <module>
2025-04-25 16:13:19 [256,059ms] [Error] [omni.kit.app._impl] [py stderr]:     main()
2025-04-25 16:13:19 [256,059ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/raise_standalone_sim.py", line 99, in main
2025-04-25 16:13:19 [256,059ms] [Error] [omni.kit.app._impl] [py stderr]:     rpc_server.server_function.on_physics_step()
2025-04-25 16:13:19 [256,059ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 239, in on_physics_step
2025-04-25 16:13:19 [256,066ms] [Error] [omni.kit.app._impl] [py stderr]:     self.on_command_step()
2025-04-25 16:13:19 [256,066ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 768, in on_command_step
2025-04-25 16:13:19 [256,067ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_robot_cfg(
2025-04-25 16:13:19 [256,067ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 192, in _init_robot_cfg
2025-04-25 16:13:19 [256,067ms] [Error] [omni.kit.app._impl] [py stderr]:     self._play()
2025-04-25 16:13:19 [256,067ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 196, in _play
2025-04-25 16:13:19 [256,068ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_robot(self.robot_cfg, self.enable_curobo)
2025-04-25 16:13:19 [256,068ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/controllers/command_controller.py", line 215, in _init_robot
2025-04-25 16:13:19 [256,068ms] [Error] [omni.kit.app._impl] [py stderr]:     self.ui_builder._init_solver(robot, enable_curobo, self.batch_num)
2025-04-25 16:13:19 [256,068ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 84, in _init_solver
2025-04-25 16:13:19 [256,106ms] [Error] [omni.kit.app._impl] [py stderr]:     self.initialize_articulation(batch_num)
2025-04-25 16:13:19 [256,106ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 604, in initialize_articulation
2025-04-25 16:13:19 [256,107ms] [Error] [omni.kit.app._impl] [py stderr]:     self._init_curobo()
2025-04-25 16:13:19 [256,107ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/app/ui_builder.py", line 661, in _init_curobo
2025-04-25 16:13:19 [256,107ms] [Error] [omni.kit.app._impl] [py stderr]:     self.curoboMotion = CuroboMotion(
2025-04-25 16:13:19 [256,107ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/root/workspace/main/server/source/genie.sim.lab/genie/sim/lab/utils/motion_gen_reacher.py", line 98, in __init__
2025-04-25 16:13:19 [256,108ms] [Error] [omni.kit.app._impl] [py stderr]:     motion_gen_config = MotionGen.load_from_robot_config(
2025-04-25 16:13:19 [256,108ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/wrap/reacher/motion_gen.py", line 612, in load_from_robot_config
2025-04-25 16:13:19 [256,121ms] [Error] [omni.kit.app._impl] [py stderr]:     robot_cfg = RobotConfig.from_dict(robot_cfg, tensor_args)
2025-04-25 16:13:19 [256,122ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/types/robot.py", line 50, in from_dict
2025-04-25 16:13:19 [256,123ms] [Error] [omni.kit.app._impl] [py stderr]:     data_dict["kinematics"] = CudaRobotModelConfig.from_config(
2025-04-25 16:13:19 [256,123ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_model.py", line 248, in from_config
2025-04-25 16:13:19 [256,129ms] [Error] [omni.kit.app._impl] [py stderr]:     generator = CudaRobotGenerator(config)
2025-04-25 16:13:19 [256,130ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 260, in __init__
2025-04-25 16:13:19 [256,142ms] [Error] [omni.kit.app._impl] [py stderr]:     self.initialize_tensors()
2025-04-25 16:13:19 [256,142ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
2025-04-25 16:13:19 [256,159ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
2025-04-25 16:13:19 [256,159ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 337, in initialize_tensors
2025-04-25 16:13:19 [256,160ms] [Error] [omni.kit.app._impl] [py stderr]:     self._build_kinematics_with_lock_joints(
2025-04-25 16:13:19 [256,160ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
2025-04-25 16:13:19 [256,161ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
2025-04-25 16:13:19 [256,161ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 673, in _build_kinematics_with_lock_joints
2025-04-25 16:13:19 [256,162ms] [Error] [omni.kit.app._impl] [py stderr]:     link_poses = self._get_link_poses(q, lock_links, kinematics_config)
2025-04-25 16:13:19 [256,162ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/contextlib.py", line 79, in inner
2025-04-25 16:13:19 [256,162ms] [Error] [omni.kit.app._impl] [py stderr]:     return func(*args, **kwds)
2025-04-25 16:13:19 [256,162ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/cuda_robot_model/cuda_robot_generator.py", line 1072, in _get_link_poses
2025-04-25 16:13:19 [256,163ms] [Error] [omni.kit.app._impl] [py stderr]:     link_pos_seq, link_quat_seq, _ = get_cuda_kinematics(
2025-04-25 16:13:19 [256,164ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/curobolib/kinematics.py", line 250, in get_cuda_kinematics
2025-04-25 16:13:19 [256,171ms] [Error] [omni.kit.app._impl] [py stderr]:     link_pos, link_quat, robot_spheres = KinematicsFusedFunction.apply(
2025-04-25 16:13:19 [256,171ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/exts/omni.isaac.ml_archive/pip_prebundle/torch/autograd/function.py", line 575, in apply
2025-04-25 16:13:19 [256,201ms] [Error] [omni.kit.app._impl] [py stderr]:     return super().apply(*args, **kwargs)  # type: ignore[misc]
2025-04-25 16:13:19 [256,201ms] [Error] [omni.kit.app._impl] [py stderr]:   File "/isaac-sim/kit/python/lib/python3.10/site-packages/curobo/curobolib/kinematics.py", line 73, in forward
2025-04-25 16:13:19 [256,201ms] [Error] [omni.kit.app._impl] [py stderr]:     r = kinematics_fused_cu.forward(
2025-04-25 16:13:19 [256,201ms] [Error] [omni.kit.app._impl] [py stderr]: RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
2025-04-25 16:13:19 [256,202ms] [Error] [omni.kit.app._impl] [py stderr]:
```

**Comment by yonhdee** [comment]
please replace the TORCH_CUDA_ARCH_LIST with one of the following strings:

> 'Kepler+Tesla', '3.7'
'Kepler', '3.5+PTX'
'Maxwell+Tegra', '5.3'
'Maxwell', '5.0;5.2+PTX'
'Pascal', '6.0;6.1+PTX'
'Volta+Tegra', '7.2'
'Volta', '7.0+PTX'
'Turing', '7.5+PTX'
'Ampere+Tegra', '8.7'
'Ampere', '8.0;8.6+PTX'
'Ada', '8.9+PTX'
'Hopper', '9.0+PTX'

more info see from https://developer.nvidia.com/cuda-gpus

see pic and explainations here https://github.com/ashawkey/stable-dreamfusion/issues/360#issuecomment-2292510049

**Comment by Ethan-Chen-plus** [comment]
> please replace the TORCH_CUDA_ARCH_LIST with one of the following strings:
> 
> > 'Kepler+Tesla', '3.7'
> > 'Kepler', '3.5+PTX'
> > 'Maxwell+Tegra', '5.3'
> > 'Maxwell', '5.0;5.2+PTX'
> > 'Pascal', '6.0;6.1+PTX'
> > 'Volta+Tegra', '7.2'
> > 'Volta', '7.0+PTX'
> > 'Turing', '7.5+PTX'
> > 'Ampere+Tegra', '8.7'
> > 'Ampere', '8.0;8.6+PTX'
> > 'Ada', '8.9+PTX'
> > 'Hopper', '9.0+PTX'
> 
> more info see from https://developer.nvidia.com/cuda-gpus
> 
> see pic and explainations here [ashawkey/stable-dreamfusion#360 (comment)](https://github.com/ashawkey/stable-dreamfusion/issues/360#issuecomment-2292510049)

Thanks a lot! I will try it.😄

**Comment by v-xchen-v** [comment]
I use A6000, 8.6 instead of 8.9 works for me. 
`export CUDA_HOME="/usr/local/cuda-11.8”
export TORCH_CUDA_ARCH_LIST="8.6”
cd /tmp/curobo
/isaac-sim/python.sh -m pip install -e .[isaacsim] --no-build-isolation`

**Comment by 1ihua1** [comment]
Hello, I am using the 50 series graphics card architecture is 12.0, and troch2.5.1 does not support architecture 12.0 in docker, does the current genie_sim support 50 series graphics cards?

> please replace the TORCH_CUDA_ARCH_LIST with one of the following strings:
> 
> > 'Kepler+Tesla', '3.7'
> > 'Kepler', '3.5+PTX'
> > 'Maxwell+Tegra', '5.3'
> > 'Maxwell', '5.0;5.2+PTX'
> > 'Pascal', '6.0;6.1+PTX'
> > 'Volta+Tegra', '7.2'
> > 'Volta', '7.0+PTX'
> > 'Turing', '7.5+PTX'
> > 'Ampere+Tegra', '8.7'
> > 'Ampere', '8.0;8.6+PTX'
> > 'Ada', '8.9+PTX'
> > 'Hopper', '9.0+PTX'
> 
> more info see from https://developer.nvidia.com/cuda-gpus
> 
> see pic and explainations here [ashawkey/stable-dreamfusion#360 (comment)](https://github.com/ashawkey/stable-dreamfusion/issues/360#issuecomment-2292510049)
